[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:app]
command=python app.py
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/app.stdout.log
stderr_logfile=/var/log/app.stderr.log
environment=FLAG_1="%(ENV_FLAG_1)s",FLAG_2="%(ENV_FLAG_2)s",FLAG_3="%(ENV_FLAG_3)s",FLAG_4="%(ENV_FLAG_4)s",FLAG_5="%(ENV_FLAG_5)s"

[program:sshd]
command=/usr/sbin/sshd -D
autostart=true
autorestart=true
stdout_logfile=/var/log/sshd.log
stderr_logfile=/var/log/sshd.log
